---
title: C28163
ms.date: 11/04/2016
ms.topic: reference
f1_keywords:
  - "C28163"
helpviewer_keywords:
  - "C28163"
ms.assetid: 24fecbde-1c96-4a45-82f7-9f47cfc0ef11
author: mikeblome
ms.author: mblome
manager: markl
ms.workload:
  - "multiple"
---
# C28163
warning C28163: The function should never be called from within a try/except block

 This warning is reported when a function is of a type that should never be enclosed in a `try/except`  block is found in a `try/except` block. The code analysis tool found at least one path in which the function called was within a `try/except` block.